package mitre

// ATT&CK Navigator layer export. Security teams already have Navigator open;
// handing them a layer file lets them overlay this estate on the matrix they
// use for everything else, instead of reading our table and retyping it.

type navVersions struct {
	Attack    string `json:"attack"`
	Navigator string `json:"navigator"`
	Layer     string `json:"layer"`
}

type navTechnique struct {
	TechniqueID string `json:"techniqueID"`
	Score       int    `json:"score"`
	Comment     string `json:"comment,omitempty"`
	Enabled     bool   `json:"enabled"`
}

type navGradient struct {
	Colors   []string `json:"colors"`
	MinValue int      `json:"minValue"`
	MaxValue int      `json:"maxValue"`
}

// NavigatorLayer is the JSON shape ATT&CK Navigator imports.
type NavigatorLayer struct {
	Name        string         `json:"name"`
	Versions    navVersions    `json:"versions"`
	Domain      string         `json:"domain"`
	Description string         `json:"description"`
	Techniques  []navTechnique `json:"techniques"`
	Gradient    navGradient    `json:"gradient"`
}

// NavigatorLayerFor scores each technique by the number of hosts it touches,
// so the heat on the matrix is "how much of my estate enables this".
func NavigatorLayerFor(name string, e EstateResult) NavigatorLayer {
	max := 1
	for _, t := range e.Techniques {
		if t.Hosts > max {
			max = t.Hosts
		}
	}

	techniques := make([]navTechnique, 0, len(e.Techniques))
	for _, t := range e.Techniques {
		comment := "Afrakav: " + itoa(t.Findings) + " finding(s)"
		if len(t.Sources) == 1 && t.Sources[0] == SourceRule {
			comment += " — inferred from plugin rules, not an official MITRE mapping"
		}
		techniques = append(techniques, navTechnique{
			TechniqueID: t.ID,
			Score:       t.Hosts,
			Comment:     comment,
			Enabled:     true,
		})
	}

	return NavigatorLayer{
		Name:   name,
		Domain: "enterprise-attack",
		Versions: navVersions{
			Attack:    "14",
			Navigator: "4.9.0",
			Layer:     "4.5",
		},
		Description: "Generated by Afrakav from Nessus findings. Scores are the " +
			"number of hosts whose findings enable the technique. Mappings marked " +
			"as inferred come from Afrakav's own plugin rules, not from MITRE.",
		Techniques: techniques,
		Gradient: navGradient{
			Colors:   []string{"#ffe8e8", "#ff6b6b", "#c00000"},
			MinValue: 0,
			MaxValue: max,
		},
	}
}

// itoa keeps the comment builder free of a fmt import for one number.
func itoa(n int) string {
	if n == 0 {
		return "0"
	}
	digits := []byte{}
	for n > 0 {
		digits = append([]byte{byte('0' + n%10)}, digits...)
		n /= 10
	}
	return string(digits)
}
